# Generated by Django 5.0.7 on 2024-09-01 11:16

from django.db import migrations, models

from utils.utils import generate_upload_path


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200416_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=generate_upload_path),
        ),
    ]
