# Generated by Django 5.0.7 on 2024-09-01 11:16

import fumetsu.templatetags.utils_extras
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200416_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=fumetsu.templatetags.utils_extras.generate_upload_path),
        ),
    ]
