# Generated by Django 5.0.7 on 2024-09-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ban',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nap_vip',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nick',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='web_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Nic o sobie nie powiem.', max_length=1024),
        ),
    ]
