# Generated by Django 5.0.7 on 2024-09-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_time_vip_profile_time_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.CharField(default='#b579d2', max_length=7),
        ),
    ]
