# Generated by Django 2.2.1 on 2019-11-03 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_bd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idd', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='akt_default.gif', upload_to='akt_post')),
            ],
        ),
        migrations.CreateModel(
            name='Key_map',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_anime', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('web_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Series_comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.CharField(max_length=254)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('key_map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fumetsu.Key_map')),
            ],
        ),
        migrations.CreateModel(
            name='Post_comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.CharField(max_length=254)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fumetsu.Info_bd')),
            ],
        ),
        migrations.CreateModel(
            name='Harmonogram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('key_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fumetsu.Key_map')),
            ],
        ),
        migrations.CreateModel(
            name='Episode_comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_ep', models.IntegerField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.CharField(max_length=254)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('key_map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fumetsu.Key_map')),
            ],
        ),
        migrations.CreateModel(
            name='Anime_list',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_anime', models.IntegerField()),
                ('content', models.TextField()),
                ('image', models.ImageField(default='av_default.gif', upload_to='anime_avatar')),
                ('image_bg', models.ImageField(default='anime_bg.jpg', upload_to='anime_avatar')),
                ('key_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fumetsu.Key_map')),
            ],
        ),
    ]
