# Generated by Django 2.2.6 on 2020-01-08 08:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fumetsu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_anime_f', models.IntegerField()),
                ('id_anime_s', models.IntegerField()),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
