# Generated by Django 2.2.6 on 2020-03-15 23:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fumetsu', '0002_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='harmonogram',
            name='day',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
