# Generated by Django 2.2.6 on 2020-04-01 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fumetsu', '0003_harmonogram_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Episode_comment',
        ),
    ]
