# Generated by Django 2.2.6 on 2020-05-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fumetsu', '0004_delete_episode_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime_list',
            name='napisy',
            field=models.FileField(blank=True, upload_to='archiwum/'),
        ),
    ]
