# Generated by Django 5.0.6 on 2024-07-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fumetsu', '0007_migrate_key_map_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime_list',
            name='key_map',
        ),
    ]
