# Generated by Django 5.0.6 on 2024-07-01 15:44

import django.db.models.deletion
from django.db import migrations, models

def copy_key_map_to_temp(apps, schema_editor):
    Series_comment = apps.get_model('fumetsu', 'Series_comment')
    models_to_update = [Series_comment]

    for model in models_to_update:
        for item in model.objects.all():
            item.key_map_temp = item.key_map.web_name
            print(item.key_map_temp)
            item.save()

def transfer_key_map_to_anime_list(apps, schema_editor):
    Anime_list = apps.get_model('fumetsu', 'Anime_list')
    Series_comment = apps.get_model('fumetsu', 'Series_comment')
    # Add more models as needed

    models_to_update = [Series_comment]  # Add all models that need updating

    for model in models_to_update:
        for item in model.objects.all():
            if not item.key_map_temp == "":  # Ensure there's a related key_map object
                try:
                    anime = Anime_list.objects.get(web_name=item.key_map_temp)
                    item.key_map = anime
                    item.save()
                except Anime_list.DoesNotExist:
                    pass  # Handle the case where there's no corresponding Anime_list


class Migration(migrations.Migration):

    dependencies = [
        ('fumetsu', '0008_remove_anime_list_key_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='series_comment',
            name='key_map_temp',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.RunPython(copy_key_map_to_temp),
        migrations.AlterField(
            model_name='series_comment',
            name='key_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fumetsu.anime_list'),
        ),
        migrations.RunPython(transfer_key_map_to_anime_list),
        migrations.RemoveField(
            model_name='series_comment',
            name='key_map_temp',
            field=models.TextField(max_length=100, null=True),
        ),

    ]
