# Generated by Django 5.0.6 on 2024-07-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fumetsu', '0010_alter_harmonogram_key_map'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Key_map',
        ),
    ]
