# Generated by Django 5.0.6 on 2024-07-04 17:52

import uuid
from django.db import migrations, models

from utils.utils import generate_web_name


def fill_old_urls_with_anime_web_names(apps, schema_editor):
    Anime_list = apps.get_model('fumetsu', 'Anime_list')
    Url_redirects = apps.get_model('fumetsu', 'Url_redirects')
    for anime in Anime_list.objects.all():
        Url_redirects.objects.create(
            old_url=anime.web_name,
            new_url=generate_web_name(anime)
        )
        anime.web_name = generate_web_name(anime)
        anime.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fumetsu', '0012_add_anilist_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url_redirects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_url', models.CharField(max_length=100)),
                ('new_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(fill_old_urls_with_anime_web_names),
    ]
