# Generated by Django 5.0.6 on 2024-07-05 18:39
import time

from django.db import migrations, models
from utils.anilist import get_series_by_name

def add_cover_from_anilist(apps, schema_editor):
    Anime_list = apps.get_model('fumetsu', 'Anime_list')
    for anime in Anime_list.objects.all():
        anilist_anime = get_series_by_name(anime.name_romaji)
        anime.cover_image = anilist_anime.cover_image.large
        anime.save()
        time.sleep(1)


class Migration(migrations.Migration):

    dependencies = [
        ('fumetsu', '0013_url_redirects'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime_list',
            name='cover_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(add_cover_from_anilist)
    ]
