# Generated by Django 5.0.6 on 2024-07-16 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fumetsu', '0016_fill_out_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
