# Generated by Django 5.0.6 on 2024-07-21 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fumetsu', '0018_anime_list_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime_list',
            name='id_anime',
        ),
    ]
