# Generated by Django 5.0.6 on 2024-07-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fumetsu', '0020_remove_anime_list_image_remove_anime_list_image_bg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime_list',
            name='title',
        ),
        migrations.RenameField(
            model_name='anime_list',
            old_name='cover_image',
            new_name='image',
        ),
    ]
