# Generated by Django 5.0.7 on 2024-09-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fumetsu', '0022_staff_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_bd',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='akt_post'),
        ),
    ]
