# Generated by Django 5.0.7 on 2024-09-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fumetsu', '0025_remove_anime_list_napisy'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime_list',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
