# Generated by Django 5.0.7 on 2024-09-01 21:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0013_rename_subtitle_paths'),
        ('fumetsu', '0025_remove_anime_list_napisy'),
        ('users', '0006_profile_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anime_list',
            new_name='AnimeSeries',
        ),
        migrations.RenameModel(
            old_name='Info_bd',
            new_name='Announcement',
        ),
        migrations.RenameModel(
            old_name='Post_comment',
            new_name='PostComment',
        ),
        migrations.RenameModel(
            old_name='Series_comment',
            new_name='SeriesComment',
        ),
        migrations.RenameModel(
            old_name='Staff_credits',
            new_name='StaffCredit',
        ),
        migrations.RenameModel(
            old_name='Url_redirects',
            new_name='UrlRedirect',
        ),
        migrations.DeleteModel(
            name='Harmonogram',
        ),
    ]
