# Generated by Django 5.0.7 on 2024-09-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fumetsu', '0027_rename_anime_list_animeseries_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='animeseries',
            table='fumetsu_anime_series',
        ),
        migrations.AlterModelTable(
            name='announcement',
            table='fumetsu_announcement',
        ),
        migrations.AlterModelTable(
            name='postcomment',
            table='fumetsu_post_comment',
        ),
        migrations.AlterModelTable(
            name='relation',
            table='fumetsu_relation',
        ),
        migrations.AlterModelTable(
            name='seriescomment',
            table='fumetsu_series_comment',
        ),
        migrations.AlterModelTable(
            name='staffcredit',
            table='fumetsu_staff_credit',
        ),
        migrations.AlterModelTable(
            name='urlredirect',
            table='fumetsu_url_redirect',
        ),
    ]
