# Generated by Django 2.2.6 on 2020-01-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_auto_20191228_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odc_name',
            name='ep_title',
            field=models.FloatField(),
        ),
    ]
