# Generated by Django 2.2.6 on 2020-04-01 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime', '0003_auto_20200105_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode_comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.CharField(max_length=254)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('key_map_ep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.Odc_name')),
            ],
        ),
    ]
