# Generated by Django 5.0.6 on 2024-07-16 17:19

import uuid
from django.db import migrations, models

from utils.utils import tag_label_to_polish


def fill_out_polish_tag_labels(apps, schema_editor):
    Tags = apps.get_model('anime', 'Tags')
    for tag in Tags.objects.all():
        tag.label_polish = tag_label_to_polish(tag.label)
        tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_clear_tags_and_drop_tags_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='label_polish',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.RunPython(fill_out_polish_tag_labels),
    ]
