# Generated by Django 2.2.6 on 2020-04-01 20:38

from django.conf import settings
from django.db import migrations

from anime.models import Odc_name
from fumetsu.models import Anime_list


def fix_episode_numbering(apps, schema_editor):
    db_series = Anime_list.objects.all()
    for series in db_series:
        episodes = Odc_name.objects.filter(key_map=series)
        for i, episode in enumerate(episodes):
            episode.ep_nr = i + 1
            episode.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime', '0007_clear_tags_and_drop_tags_map'),
    ]

    operations = [
        migrations.RunPython(fix_episode_numbering),
    ]
