# Generated by Django 5.0.7 on 2024-09-01 14:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_fix_episode_numbering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags_map',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='odc_name',
            name='ep_title',
        ),
    ]
