# Generated by Django 5.0.7 on 2024-09-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_remove_odc_name_ep_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odc_name',
            old_name='subtitles',
            new_name='napisy',
        ),
    ]
