# Generated by Django 5.0.7 on 2024-09-01 16:02

from django.db import migrations


def fix_subtitle_paths(apps, schema_editor):
    db_episodes = apps.get_model('anime', 'Odc_name').objects.all()
    for episode in db_episodes:
        old_path = episode.subtitles.name
        new_path = old_path.replace('napisy', 'subtitles')
        episode.subtitles.name = new_path
        episode.save()


class Migration(migrations.Migration):
    dependencies = [
        ('anime', '0012_rename_napisy_odc_name_subtitles'),
    ]

    operations = [
        migrations.RunPython(fix_subtitle_paths),
    ]
