# Generated by Django 5.0.7 on 2024-09-01 21:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0013_rename_subtitle_paths'),
        ('fumetsu', '0027_rename_anime_list_animeseries_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Odc_name',
            new_name='AnimeEpisode',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='AnimePost',
        ),
        migrations.RenameModel(
            old_name='Episode_comment',
            new_name='EpisodeComment',
        ),
        migrations.RenameModel(
            old_name='Anime_url',
            new_name='Player',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RemoveField(
            model_name='player_valid',
            name='key_map_ep',
        ),
        migrations.DeleteModel(
            name='Player_valid',
        ),
    ]
