# Generated by Django 5.0.7 on 2024-09-01 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0014_rename_odc_name_animeepisode_rename_post_animepost_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='animeepisode',
            table='fumetsu_anime_episode',
        ),
        migrations.AlterModelTable(
            name='animepost',
            table='fumetsu_anime_post',
        ),
        migrations.AlterModelTable(
            name='episodecomment',
            table='fumetsu_episode_comment',
        ),
        migrations.AlterModelTable(
            name='player',
            table='fumetsu_player',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='fumetsu_tag',
        ),
    ]
